// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoMateProjectShare.Data;

namespace YoMateProjectShare.Migrations
{
    [DbContext(typeof(YoMateProjectShareContext))]
    [Migration("20201201043509_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YoMateProjectShare.Models.ProjectList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectListId");

                    b.ToTable("ProjectList");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProjectList");
                });

            modelBuilder.Entity("YoMateProjectShare.Models.Projects", b =>
                {
                    b.HasBaseType("YoMateProjectShare.Models.ProjectList");

                    b.Property<string>("AbstractText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Projects");
                });

            modelBuilder.Entity("YoMateProjectShare.Models.ProjectList", b =>
                {
                    b.HasOne("YoMateProjectShare.Models.ProjectList", null)
                        .WithMany("projects")
                        .HasForeignKey("ProjectListId");
                });
#pragma warning restore 612, 618
        }
    }
}
